const DB_NAME='dispatchmate-secure-assets',DB_VERSION=1,KEY_STORE='keys',ASSET_STORE='assets'
export interface EncryptedAsset {assetId:string;contentHash:string;encryptedBytes:number;iv:string;encryption:'AES-GCM';mediaType:string}
const b64=(bytes:Uint8Array)=>{let value='';for(const byte of bytes)value+=String.fromCharCode(byte);return btoa(value)}
const hex=(bytes:Uint8Array)=>Array.from(bytes,byte=>byte.toString(16).padStart(2,'0')).join('')
function openDb(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(KEY_STORE))request.result.createObjectStore(KEY_STORE);if(!request.result.objectStoreNames.contains(ASSET_STORE))request.result.createObjectStore(ASSET_STORE,{keyPath:'assetId'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
function transaction<T>(db:IDBDatabase,store:string,mode:IDBTransactionMode,run:(objectStore:IDBObjectStore)=>IDBRequest<T>){return new Promise<T>((resolve,reject)=>{const tx=db.transaction(store,mode),request=run(tx.objectStore(store));request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function keyFor(userId:string){const db=await openDb();let key=await transaction<CryptoKey|undefined>(db,KEY_STORE,'readonly',store=>store.get(userId));if(!key){key=await crypto.subtle.generateKey({name:'AES-GCM',length:256},false,['encrypt','decrypt']);await transaction(db,KEY_STORE,'readwrite',store=>store.put(key!,userId))}return key}
export async function encryptOfflineAsset(file:File,userId:string,incidentId:string):Promise<EncryptedAsset>{if(!userId||!incidentId)throw new Error('사용자와 출동 정보가 필요합니다.');const plaintext=await file.arrayBuffer(),contentHash=hex(new Uint8Array(await crypto.subtle.digest('SHA-256',plaintext))),iv=crypto.getRandomValues(new Uint8Array(12)),key=await keyFor(userId),ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,plaintext),assetId=crypto.randomUUID(),record={assetId,userId,incidentId,mediaType:file.type||'application/octet-stream',fileName:file.name,contentHash,iv:b64(iv),ciphertext,createdAt:new Date().toISOString()};const db=await openDb();await transaction(db,ASSET_STORE,'readwrite',store=>store.put(record));return{assetId,contentHash,encryptedBytes:ciphertext.byteLength,iv:record.iv,encryption:'AES-GCM',mediaType:record.mediaType}}
export async function deleteAllEncryptedAssets(){const db=await openDb();await transaction(db,ASSET_STORE,'readwrite',store=>store.clear());await transaction(db,KEY_STORE,'readwrite',store=>store.clear())}
