import { BadRequestException, ForbiddenException, Injectable, NotFoundException, UnauthorizedException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { InjectRepository } from '@nestjs/typeorm';
import { createHash, createHmac, timingSafeEqual } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { Repository } from 'typeorm';
import { Alert } from '../alerts/entities/alert.entity';
import { AlertsService } from '../alerts/alerts.service';
import { AuthenticatedUser } from '../auth/authenticated-user.interface';
import { OrganizationScopeService } from '../common/organization-scope/organization-scope.service';

const sha256=(value:Buffer|string)=>createHash('sha256').update(value).digest('hex');

@Injectable()
export class FieldIntelligenceService {
  constructor(@InjectRepository(Alert) private readonly db:Repository<Alert>,private readonly config:ConfigService,private readonly alerts:AlertsService,private readonly orgScope:OrganizationScopeService){}
  private operator(user:AuthenticatedUser){if(!['ADMIN','COMMANDER'].includes(user.role))throw new ForbiddenException();}
  private admin(user:AuthenticatedUser){if(user.role!=='ADMIN')throw new ForbiddenException();}
  private secret(provider:string){const key=provider.toUpperCase().replace(/[^A-Z0-9]/g,'_'),file=this.config.get<string>(`PROVIDER_${key}_WEBHOOK_SECRET_FILE`);if(file)return readFileSync(file,'utf8').trim();return this.config.get<string>(`PROVIDER_${key}_WEBHOOK_SECRET`);}

  async webhook(provider:string,eventId:string,eventType:string,signature:string|undefined,raw:Buffer){
    if(!/^[a-z0-9_-]{2,40}$/i.test(provider)||!eventId||!eventType)throw new BadRequestException();
    const secret=this.secret(provider);if(!secret)throw new UnauthorizedException('공급자 webhook 비밀이 설정되지 않았습니다.');
    const expected=createHmac('sha256',secret).update(raw).digest('hex'),given=(signature??'').replace(/^sha256=/,'');
    const valid=/^[a-f0-9]{64}$/i.test(given)&&timingSafeEqual(Buffer.from(expected),Buffer.from(given.toLowerCase()));
    if(!valid)throw new UnauthorizedException('webhook 서명이 유효하지 않습니다.');
    const inserted=await this.db.query(`INSERT INTO provider_webhook_receipts(provider_key,external_event_id,event_type,payload_hash,signature_valid,processing_status,processed_at) VALUES($1,$2,$3,$4,true,'PROCESSED',now()) ON CONFLICT(provider_key,external_event_id) DO NOTHING RETURNING receipt_id AS "receiptId",processing_status AS status`,[provider,eventId,eventType,sha256(raw)]);
    if(inserted.length)return inserted[0];
    const existing=await this.db.query(`SELECT receipt_id AS "receiptId" FROM provider_webhook_receipts WHERE provider_key=$1 AND external_event_id=$2`,[provider,eventId]);
    return{...existing[0],status:'DUPLICATE'};
  }

  async uploadChunk(user:AuthenticatedUser,body:any){
    if(!body.chunkId||!body.assetId||!Number.isInteger(Number(body.chunkIndex))||Number(body.byteSize)<=0||!/^[a-f0-9]{64}$/i.test(body.contentHash??''))throw new BadRequestException();
    const owned=await this.db.query(`SELECT 1 FROM offline_asset_manifests WHERE asset_id=$1 AND user_id=$2`,[body.assetId,user.userId]);if(!owned.length)throw new ForbiddenException();
    return (await this.db.query(`INSERT INTO offline_upload_chunks(chunk_id,asset_id,chunk_index,byte_size,content_hash,storage_uri,status) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(asset_id,chunk_index) DO UPDATE SET content_hash=EXCLUDED.content_hash,byte_size=EXCLUDED.byte_size RETURNING chunk_id AS "chunkId",status`,[body.chunkId,body.assetId,body.chunkIndex,body.byteSize,body.contentHash.toLowerCase(),body.storageUri??null,body.storageUri?'UPLOADED':'REGISTERED']))[0];
  }

  async importBim(modelId:string,user:AuthenticatedUser,body:any){
    this.admin(user);const elements=Array.isArray(body.elements)?body.elements:[];if(!elements.length||elements.length>500)throw new BadRequestException('BIM 요소는 1~500개씩 가져올 수 있습니다.');
    const allowed=['ROOM','STAIR','EXIT','FIRE_DOOR','HYDRANT','HAZARD','ASSEMBLY_POINT'];
    return this.db.manager.transaction(async manager=>{let count=0;for(const element of elements){if(!element.externalId||!element.label||!allowed.includes(element.elementType))throw new BadRequestException('잘못된 BIM 요소입니다.');await manager.query(`INSERT INTO building_model_elements(model_id,external_id,floor_label,element_type,label,geometry,properties,accessible) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,$8) ON CONFLICT(model_id,external_id) DO UPDATE SET floor_label=EXCLUDED.floor_label,element_type=EXCLUDED.element_type,label=EXCLUDED.label,geometry=EXCLUDED.geometry,properties=EXCLUDED.properties,accessible=EXCLUDED.accessible`,[modelId,element.externalId,element.floorLabel??null,element.elementType,element.label,JSON.stringify(element.geometry??{}),JSON.stringify(element.properties??{}),element.accessible!==false]);count++;}return{imported:count};});
  }

  async analyzeTranscript(id:string,user:AuthenticatedUser){
    this.operator(user);const transcript=(await this.db.query(`SELECT transcript_id,incident_id,transcript FROM radio_transcripts WHERE transcript_id=$1`,[id]))[0];if(!transcript)throw new NotFoundException();
    await this.orgScope.assertIncident(user,transcript.incident_id);
    const rules=[{words:['mayday','메이데이','구조 요청'],keyword:'MAYDAY',severity:'CRITICAL'},{words:['철수','evacuate','대피'],keyword:'EVACUATE',severity:'CRITICAL'},{words:['통신 두절','연락 안'],keyword:'COMMS_LOSS',severity:'WARNING'},{words:['부상','환자'],keyword:'CASUALTY',severity:'WARNING'}];
    const detections=[];for(const rule of rules){if(rule.words.some(word=>transcript.transcript.toLowerCase().includes(word))){const row=(await this.db.query(`INSERT INTO radio_keyword_detections(transcript_id,incident_id,keyword,severity,confidence,context_excerpt) VALUES($1,$2,$3,$4,.95,$5) RETURNING detection_id AS "detectionId",keyword,severity`,[id,transcript.incident_id,rule.keyword,rule.severity,transcript.transcript.slice(0,240)]))[0];detections.push(row);if(rule.severity==='CRITICAL')await this.alerts.createFromSystem({incidentId:transcript.incident_id,alertType:'RISK_WARNING',message:`[무전 감지] ${rule.keyword}`,sourceType:'HUMAN',automationKey:`radio:${id}:${rule.keyword}`});}}
    return{detections,disclaimer:'키워드 규칙 기반 보조 기능이며 원본 무전을 사람이 확인해야 합니다.'};
  }

  async attachHandoverSignature(handoverId:string,user:AuthenticatedUser,body:any){
    this.operator(user);if(!['SENDER','RECEIVER'].includes(body.party)||!body.signatureId)throw new BadRequestException();
    const handover=(await this.db.query(`SELECT incident_id FROM patient_handovers WHERE handover_id=$1`,[handoverId]))[0];if(!handover)throw new NotFoundException();
    await this.orgScope.assertIncident(user,handover.incident_id);
    const signature=(await this.db.query(`SELECT verification_status FROM electronic_signatures WHERE signature_id=$1`,[body.signatureId]))[0];if(!signature||signature.verification_status!=='VALID')throw new BadRequestException('검증 완료된 전자서명만 연결할 수 있습니다.');
    const column=body.party==='SENDER'?'sender_signature_id':'receiver_signature_id';await this.db.query(`INSERT INTO handover_signature_requirements(handover_id,${column},receiving_organization) VALUES($1,$2,$3) ON CONFLICT(handover_id) DO UPDATE SET ${column}=EXCLUDED.${column},receiving_organization=COALESCE(EXCLUDED.receiving_organization,handover_signature_requirements.receiving_organization),updated_at=now()`,[handoverId,body.signatureId,body.receivingOrganization??null]);
    return (await this.db.query(`UPDATE handover_signature_requirements SET verification_status=CASE WHEN sender_signature_id IS NOT NULL AND receiver_signature_id IS NOT NULL THEN 'VERIFIED' ELSE 'PARTIAL' END,received_at=CASE WHEN sender_signature_id IS NOT NULL AND receiver_signature_id IS NOT NULL THEN now() ELSE received_at END WHERE handover_id=$1 RETURNING handover_id AS "handoverId",verification_status AS "verificationStatus"`,[handoverId]))[0];
  }

  async observation(incidentId:string,user:AuthenticatedUser,body:any){this.operator(user);await this.orgScope.assertIncident(user,incidentId);if(!['WEATHER','ROAD_CLOSURE','SHELTER','WATER_SUPPLY','HAZMAT','HOSPITAL'].includes(body.dataType)||!body.sourceName)throw new BadRequestException();return (await this.db.query(`INSERT INTO public_data_observations(incident_id,data_type,source_name,external_ref,observed_at,expires_at,confidence,payload) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb) ON CONFLICT(source_name,external_ref,observed_at) DO UPDATE SET payload=EXCLUDED.payload,confidence=EXCLUDED.confidence RETURNING observation_id AS "observationId"`,[incidentId,body.dataType,body.sourceName,body.externalRef??null,body.observedAt??new Date().toISOString(),body.expiresAt??null,body.confidence??'UNKNOWN',JSON.stringify(body.payload??{})]))[0];}

  async flight(incidentId:string,user:AuthenticatedUser,body:any){this.operator(user);await this.orgScope.assertIncident(user,incidentId);if(!['RECON','THERMAL_SEARCH','PERSON_SEARCH','HAZMAT','MAPPING'].includes(body.missionType)||!Array.isArray(body.route)||!body.route.length)throw new BadRequestException();return (await this.db.query(`INSERT INTO drone_flight_plans(incident_id,device_id,mission_type,route,max_altitude_m,return_point,battery_minimum_percent,created_by) VALUES($1,$2,$3,$4::jsonb,$5,$6::jsonb,$7,$8) RETURNING flight_id AS "flightId",approval_status AS "approvalStatus"`,[incidentId,body.deviceId??null,body.missionType,JSON.stringify(body.route),body.maxAltitudeM??120,JSON.stringify(body.returnPoint??body.route[0]),body.batteryMinimumPercent??30,user.userId]))[0];}
  async approveFlight(id:string,user:AuthenticatedUser,decision:string){this.operator(user);if(!['APPROVED','REJECTED'].includes(decision))throw new BadRequestException();const plan=(await this.db.query(`SELECT incident_id FROM drone_flight_plans WHERE flight_id=$1`,[id]))[0];if(!plan)throw new NotFoundException();await this.orgScope.assertIncident(user,plan.incident_id);const rows=await this.db.query(`UPDATE drone_flight_plans SET approval_status=$3,approved_by=$2 WHERE flight_id=$1 AND approval_status='PENDING' AND created_by<>$2 RETURNING flight_id AS "flightId",approval_status AS "approvalStatus"`,[id,user.userId,decision]);if(!rows.length)throw new BadRequestException('임무 작성자와 다른 지휘관의 승인이 필요합니다.');return rows[0];}

  async decisionBoard(incidentId:string,user:AuthenticatedUser){this.operator(user);await this.orgScope.assertIncident(user,incidentId);const [mayday,objectives,circuits,observations]=await Promise.all([this.db.query(`SELECT COUNT(*)::int AS count FROM emergency_signals WHERE incident_id=$1 AND status IN ('ACTIVE','ACKNOWLEDGED')`,[incidentId]),this.db.query(`SELECT COUNT(*)::int AS count FROM tactical_objectives WHERE incident_id=$1 AND status='BLOCKED'`,[incidentId]),this.db.query(`SELECT COUNT(*)::int AS count FROM provider_circuit_breakers WHERE state='OPEN'`),this.db.query(`SELECT data_type AS "dataType",confidence,observed_at AS "observedAt",payload FROM public_data_observations WHERE incident_id=$1 AND (expires_at IS NULL OR expires_at>now()) ORDER BY observed_at DESC LIMIT 20`,[incidentId])]);const proposed=[];if(Number(mayday[0].count))proposed.push(await this.recommend(incidentId,'RESCUE_PRIORITY','활성 MAYDAY 구조팀 우선 배치',{activeMaydays:mayday[0].count},1));if(Number(objectives[0].count))proposed.push(await this.recommend(incidentId,'BLOCKED_OBJECTIVE','차단된 전술 목표 재할당',{blockedObjectives:objectives[0].count},2));if(Number(circuits[0].count))proposed.push(await this.recommend(incidentId,'COMMUNICATION_FALLBACK','대체 통신 채널 확인',{openCircuits:circuits[0].count},1));const existing=await this.db.query(`SELECT recommendation_id AS "recommendationId",recommendation_type AS "recommendationType",title,rationale,source_freshness AS "sourceFreshness",priority,status,decision_reason AS "decisionReason" FROM decision_recommendations WHERE incident_id=$1 AND status IN ('PROPOSED','ACCEPTED') ORDER BY priority,created_at DESC`,[incidentId]);return{recommendations:existing,observations,generated:proposed.length,disclaimer:'권고는 자동 명령이 아니며 지휘관 판단과 승인이 필요합니다.'};}
  private async recommend(incidentId:string,type:string,title:string,rationale:any,priority:number){return this.db.query(`INSERT INTO decision_recommendations(incident_id,recommendation_type,title,rationale,source_freshness,priority) SELECT $1::uuid,$2::varchar,$3::varchar,$4::jsonb,$5::jsonb,$6::integer WHERE NOT EXISTS(SELECT 1 FROM decision_recommendations WHERE incident_id=$1::uuid AND recommendation_type=$2::varchar AND status IN ('PROPOSED','ACCEPTED'))`,[incidentId,type,title,JSON.stringify(rationale),JSON.stringify({generatedAt:new Date().toISOString()}),priority]);}
  async decision(id:string,user:AuthenticatedUser,status:string,reason:string){this.operator(user);if(!['ACCEPTED','REJECTED','COMPLETED'].includes(status)||!reason?.trim())throw new BadRequestException();const recommendation=(await this.db.query(`SELECT incident_id FROM decision_recommendations WHERE recommendation_id=$1`,[id]))[0];if(!recommendation)throw new NotFoundException();await this.orgScope.assertIncident(user,recommendation.incident_id);const rows=await this.db.query(`UPDATE decision_recommendations SET status=$2,decision_reason=$3,decided_by=$4,decided_at=now() WHERE recommendation_id=$1 RETURNING recommendation_id AS "recommendationId",status`,[id,status,reason.trim(),user.userId]);if(!rows.length)throw new NotFoundException();return rows[0];}

  async anomaly(user:AuthenticatedUser,body:any){this.admin(user);if(!['LOGIN_FAILURE_BURST','MASS_READ','LOCATION_ACCESS','DEVICE_CHANGE','PRIVILEGE_ESCALATION','SIGNATURE_FAILURE'].includes(body.anomalyType))throw new BadRequestException();if(body.incidentId)await this.orgScope.assertIncident(user,body.incidentId);return (await this.db.query(`INSERT INTO security_anomaly_events(user_id,incident_id,anomaly_type,risk_score,evidence) VALUES($1,$2,$3,$4,$5::jsonb) RETURNING anomaly_id AS "anomalyId",status`,[body.userId??null,body.incidentId??null,body.anomalyType,body.riskScore,JSON.stringify(body.evidence??{})]))[0];}
  async kpi(incidentId:string,user:AuthenticatedUser){this.operator(user);await this.orgScope.assertIncident(user,incidentId);const row=(await this.db.query(`SELECT i.reported_at,i.closed_at,(SELECT MIN(recorded_at) FROM responder_status_logs WHERE incident_id=i.incident_id) AS first_status,(SELECT AVG(EXTRACT(EPOCH FROM(received_at-queued_at))) FROM alert_deliveries d JOIN alerts a ON a.alert_id=d.alert_id WHERE a.incident_id=i.incident_id AND received_at IS NOT NULL) AS delivery_seconds,(SELECT AVG(EXTRACT(EPOCH FROM(acknowledged_at-activated_at))) FROM emergency_signals WHERE incident_id=i.incident_id AND acknowledged_at IS NOT NULL) AS mayday_ack_seconds FROM incidents i WHERE i.incident_id=$1`,[incidentId]))[0];if(!row)throw new NotFoundException();const metrics={firstTelemetrySeconds:row.first_status?Math.round((new Date(row.first_status).getTime()-new Date(row.reported_at).getTime())/1000):null,averageDeliverySeconds:row.delivery_seconds==null?null:Number(row.delivery_seconds),averageMaydayAckSeconds:row.mayday_ack_seconds==null?null:Number(row.mayday_ack_seconds),durationSeconds:row.closed_at?Math.round((new Date(row.closed_at).getTime()-new Date(row.reported_at).getTime())/1000):null};return (await this.db.query(`INSERT INTO operational_kpi_snapshots(incident_id,period_start,period_end,metrics) VALUES($1,$2,COALESCE($3,now()),$4::jsonb) ON CONFLICT(incident_id,period_start,period_end) DO UPDATE SET metrics=EXCLUDED.metrics RETURNING snapshot_id AS "snapshotId",metrics`,[incidentId,row.reported_at,row.closed_at,JSON.stringify(metrics)]))[0];}
}
