import { Injectable,Logger,OnModuleDestroy,OnModuleInit } from '@nestjs/common';import { ConfigService } from '@nestjs/config';import { InjectRepository } from '@nestjs/typeorm';import { Repository } from 'typeorm';import { Alert } from '../alerts/entities/alert.entity';import { AlertsService } from '../alerts/alerts.service';
@Injectable()
export class AutomationService implements OnModuleInit,OnModuleDestroy{private timer?:NodeJS.Timeout;private running=false;private readonly logger=new Logger(AutomationService.name);constructor(@InjectRepository(Alert)private readonly db:Repository<Alert>,private readonly alerts:AlertsService,private readonly config:ConfigService){}
 onModuleInit(){this.timer=setInterval(()=>void this.run(),30000)}onModuleDestroy(){if(this.timer)clearInterval(this.timer)}
 async run(){if(this.running)return;this.running=true;try{await this.safety();await this.channels()}catch(error){this.logger.error('운영 자동화 점검 실패',error)}finally{this.running=false}}
 private async safety(){const rows=await this.db.query(`SELECT DISTINCT ON(s.incident_id,s.user_id) s.incident_id AS "incidentId",s.user_id AS "userId",s.recorded_at AS "recordedAt",s.risk_level AS "riskLevel",s.connection_status AS "connectionStatus",s.biometric_data AS "biometricData",s.environment_data AS "environmentData" FROM responder_status_logs s JOIN incidents i ON i.incident_id=s.incident_id WHERE i.status<>'CLOSED' ORDER BY s.incident_id,s.user_id,s.recorded_at DESC`);for(const row of rows){const rules:{code:string;message:string}[]=[];if(row.riskLevel==='DANGER')rules.push({code:'RISK_DANGER',message:'대원 위험 상태 보고'});if(row.connectionStatus==='DISCONNECTED')rules.push({code:'CONNECTION_LOST',message:'대원 통신 두절'});if(Number(row.biometricData?.heartRate)>180)rules.push({code:'HEART_RATE_HIGH',message:'대원 심박수 180 초과'});if(Number(row.environmentData?.ambientTemperature)>80)rules.push({code:'TEMPERATURE_HIGH',message:'주변 온도 80℃ 초과'});for(const rule of rules){const key=`safety:${row.incidentId}:${row.userId}:${rule.code}:${new Date(row.recordedAt).toISOString()}`;await this.alerts.createFromSystem({incidentId:row.incidentId,alertType:'RISK_WARNING',message:`[자동 안전 경보] ${rule.message}`,sourceType:'SENSOR',targetUserId:row.userId,automationKey:key});await this.db.query(`INSERT INTO safety_alert_state(incident_id,user_id,rule_code,last_source_at) VALUES($1,$2,$3,$4) ON CONFLICT(incident_id,user_id,rule_code) DO UPDATE SET last_source_at=EXCLUDED.last_source_at,last_alerted_at=now()`,[row.incidentId,row.userId,rule.code,row.recordedAt]); }} }
 private async channels(){const candidates=await this.db.query(`SELECT d.alert_id AS "alertId",d.user_id AS "userId",u.phone,a.message,d.queued_at AS "queuedAt",EXTRACT(EPOCH FROM(now()-d.queued_at)) AS age FROM alert_deliveries d JOIN alerts a ON a.alert_id=d.alert_id JOIN users u ON u.user_id=d.user_id JOIN incidents i ON i.incident_id=a.incident_id WHERE d.received_at IS NULL AND i.status<>'CLOSED' AND EXTRACT(EPOCH FROM(now()-d.queued_at))>=30`);for(const row of candidates){await this.channel(row,'SMS',30);if(Number(row.age)>=90)await this.channel(row,'VOICE',90)}}
 private async channel(row:any,channel:'SMS'|'VOICE',minimumAge:number){if(Number(row.age)<minimumAge)return;const existing=await this.db.query(`SELECT status,next_retry_at FROM notification_channel_attempts WHERE alert_id=$1 AND user_id=$2 AND channel=$3`,[row.alertId,row.userId,channel]);if(existing[0]?.status==='SENT'||(existing[0]?.next_retry_at&&new Date(existing[0].next_retry_at)>new Date()))return;const url=this.config.get<string>(`${channel}_GATEWAY_URL`);let status='UNAVAILABLE';let error:string|null='게이트웨이 미설정';if(url&&row.phone){try{const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',...(this.config.get('MULTICHANNEL_TOKEN')?{Authorization:`Bearer ${this.config.get('MULTICHANNEL_TOKEN')}`}:{})},body:JSON.stringify({to:row.phone,message:row.message,alertId:row.alertId}),signal:AbortSignal.timeout(5000)});status=response.ok?'SENT':'FAILED';error=response.ok?null:`HTTP ${response.status}`}catch(e){status='FAILED';error=e instanceof Error?e.message:'전송 실패'}}else if(!row.phone)error='대원 전화번호 없음';await this.db.query(`INSERT INTO notification_channel_attempts(alert_id,user_id,channel,status,last_error,next_retry_at) VALUES($1::uuid,$2::uuid,$3::varchar,$4::varchar,$5,CASE WHEN $4::varchar='SENT' THEN NULL ELSE now()+interval '5 minutes' END) ON CONFLICT(alert_id,user_id,channel) DO UPDATE SET status=EXCLUDED.status,last_error=EXCLUDED.last_error,last_attempt_at=now(),attempt_count=notification_channel_attempts.attempt_count+1,next_retry_at=EXCLUDED.next_retry_at`,[row.alertId,row.userId,channel,status,error]);}
}
