import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { ConfigService } from '@nestjs/config';
import { Repository } from 'typeorm';
import { Alert } from '../alerts/entities/alert.entity';
import { AlertsService } from '../alerts/alerts.service';
import { AuthenticatedUser } from '../auth/authenticated-user.interface';
import { OrganizationScopeService } from '../common/organization-scope/organization-scope.service';

@Injectable()
export class MissionService {
  constructor(@InjectRepository(Alert) private readonly db:Repository<Alert>,private readonly alerts:AlertsService,private readonly config:ConfigService,private readonly orgScope:OrganizationScopeService){}
  private operator(user:AuthenticatedUser){if(!['ADMIN','COMMANDER'].includes(user.role))throw new ForbiddenException();}
  private admin(user:AuthenticatedUser){if(user.role!=='ADMIN')throw new ForbiddenException();}

  async control(incidentId:string,user:AuthenticatedUser){
    await this.db.query(`INSERT INTO incident_sop_items(incident_id,position,label,required)
      SELECT i.incident_id,t.position,t.label,t.required FROM incidents i JOIN sop_template_items t ON t.incident_type=i.incident_type
      WHERE i.incident_id=$1 ON CONFLICT(incident_id,position) DO NOTHING`,[incidentId]);
    const [commands,sop,resources,floors,markers,packets,attempts,inventory]=await Promise.all([
      this.db.query(`SELECT c.command_id AS "commandId",c.command_type AS "commandType",c.assignee_id AS "assigneeId",u.name AS "assigneeName",c.title,c.details,c.status,c.due_at AS "dueAt",c.issued_at AS "issuedAt" FROM incident_commands c LEFT JOIN users u ON u.user_id=c.assignee_id WHERE c.incident_id=$1 ORDER BY c.issued_at DESC`,[incidentId]),
      this.db.query(`SELECT sop_item_id AS "sopItemId",position,label,required,status,note,completed_at AS "completedAt" FROM incident_sop_items WHERE incident_id=$1 ORDER BY position`,[incidentId]),
      this.db.query(`SELECT r.request_id AS "requestId",r.item_name AS "itemName",r.quantity,r.status,r.requested_at AS "requestedAt",u.name AS "requestedByName" FROM incident_resource_requests r JOIN users u ON u.user_id=r.requested_by WHERE r.incident_id=$1 ORDER BY r.requested_at DESC`,[incidentId]),
      this.db.query(`SELECT floor_id AS "floorId",floor_label AS "floorLabel",width_m AS "widthM",height_m AS "heightM" FROM indoor_floors WHERE incident_id=$1 ORDER BY floor_label`,[incidentId]),
      this.db.query(`SELECT marker_id AS "markerId",floor_id AS "floorId",marker_type AS "markerType",label,x_percent AS "xPercent",y_percent AS "yPercent" FROM operational_markers WHERE incident_id=$1 ORDER BY created_at`,[incidentId]),
      this.db.query(`SELECT packet_id AS "packetId",agency_name AS "agencyName",classification,summary,status,created_at AS "createdAt",shared_at AS "sharedAt" FROM collaboration_packets WHERE incident_id=$1 ORDER BY created_at DESC`,[incidentId]),
      this.db.query(`SELECT n.alert_id AS "alertId",n.user_id AS "userId",n.channel,n.status,n.attempt_count AS "attemptCount",n.last_error AS "lastError",n.last_attempt_at AS "lastAttemptAt" FROM notification_channel_attempts n JOIN alerts a ON a.alert_id=n.alert_id WHERE a.incident_id=$1 ORDER BY n.last_attempt_at DESC`,[incidentId]),
      this.db.query(`SELECT resource_id AS "resourceId",resource_type AS "resourceType",name,total_quantity AS "totalQuantity",available_quantity AS "availableQuantity",unit,status FROM operational_resources ORDER BY resource_type,name`)]);
    if(user.role==='RESPONDER')return {commands:commands.filter((c:any)=>!c.assigneeId||c.assigneeId===user.userId),sop,resources,floors,markers,inventory,packets:[],channelAttempts:[]};
    this.operator(user);return {commands,sop,resources,floors,markers,inventory,packets,channelAttempts:attempts};
  }

  async createCommand(incidentId:string,user:AuthenticatedUser,body:any){this.operator(user);const types=['ASSIGN_TASK','HANDOVER','EVACUATE','MUSTER'];if(!types.includes(body.commandType)||!body.title?.trim())throw new BadRequestException('지휘 명령을 확인하세요.');if(body.assigneeId){const assigned=await this.db.query('SELECT 1 FROM incident_assignments WHERE incident_id=$1 AND user_id=$2',[incidentId,body.assigneeId]);if(!assigned.length)throw new BadRequestException('배정된 대원만 지정할 수 있습니다.');}
    const row=(await this.db.query(`INSERT INTO incident_commands(incident_id,command_type,assignee_id,issued_by,title,details,due_at) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING command_id AS "commandId",status`,[incidentId,body.commandType,body.assigneeId||null,user.userId,body.title.trim(),body.details?.trim()||null,body.dueAt||null]))[0];
    await this.alerts.createFromSystem({incidentId,alertType:body.commandType==='EVACUATE'?'EVACUATION':'STATUS_CHANGE',message:`[지휘 명령] ${body.title.trim()}`,sourceType:'HUMAN',targetUserId:body.assigneeId||null,automationKey:`command:${row.commandId}`});return row;}
  async commandStatus(id:string,user:AuthenticatedUser,status:string){if(!['ACKNOWLEDGED','COMPLETED','CANCELLED'].includes(status))throw new BadRequestException();const command=(await this.db.query(`SELECT incident_id FROM incident_commands WHERE command_id=$1`,[id]))[0];if(!command)throw new NotFoundException();await this.orgScope.assertIncident(user,command.incident_id);const params:any[]=[id,status];let scope='';if(user.role==='RESPONDER'){scope=' AND assignee_id=$3';params.push(user.userId)}else this.operator(user);const rows=await this.db.query(`UPDATE incident_commands SET status=$2,updated_at=now() WHERE command_id=$1${scope} AND status NOT IN ('COMPLETED','CANCELLED') RETURNING command_id AS "commandId",status`,params);if(!rows.length)throw new ForbiddenException('변경할 수 없는 명령입니다.');return rows[0];}
  async sopStatus(id:string,user:AuthenticatedUser,status:string,note?:string){if(!['COMPLETED','SKIPPED','PENDING'].includes(status))throw new BadRequestException();const item=(await this.db.query(`SELECT incident_id FROM incident_sop_items WHERE sop_item_id=$1`,[id]))[0];if(!item)throw new NotFoundException();await this.orgScope.assertIncident(user,item.incident_id);const scope=user.role==='RESPONDER'?` AND EXISTS(SELECT 1 FROM incident_assignments a WHERE a.incident_id=incident_sop_items.incident_id AND a.user_id=$5::uuid)`:'';if(user.role!=='RESPONDER')this.operator(user);const rows=await this.db.query(`UPDATE incident_sop_items SET status=$2::varchar,note=$3,completed_by=CASE WHEN $2::varchar='PENDING' THEN NULL ELSE $4::uuid END,completed_at=CASE WHEN $2::varchar='PENDING' THEN NULL ELSE now() END WHERE sop_item_id=$1${scope} RETURNING sop_item_id AS "sopItemId",status`,[id,status,note?.trim()||null,user.userId,user.userId]);if(!rows.length)throw new ForbiddenException();return rows[0];}
  async requestResource(incidentId:string,user:AuthenticatedUser,body:any){if(!Number.isInteger(body.quantity)||body.quantity<1)throw new BadRequestException();let itemName=body.itemName?.trim();if(body.resourceId){const rows=await this.db.query(`SELECT name FROM operational_resources WHERE resource_id=$1`,[body.resourceId]);if(!rows.length)throw new NotFoundException();itemName=rows[0].name}if(!itemName)throw new BadRequestException();return (await this.db.query(`INSERT INTO incident_resource_requests(incident_id,resource_id,item_name,quantity,requested_by) VALUES($1,$2,$3,$4,$5) RETURNING request_id AS "requestId",status`,[incidentId,body.resourceId||null,itemName,body.quantity,user.userId]))[0];}
  async resourceStatus(id:string,user:AuthenticatedUser,status:string){this.operator(user);if(!['APPROVED','FULFILLED','REJECTED'].includes(status))throw new BadRequestException();const request0=(await this.db.query(`SELECT incident_id FROM incident_resource_requests WHERE request_id=$1`,[id]))[0];if(!request0)throw new NotFoundException();await this.orgScope.assertIncident(user,request0.incident_id);return this.db.manager.transaction(async manager=>{const requests=await manager.query(`SELECT resource_id,quantity,status FROM incident_resource_requests WHERE request_id=$1 FOR UPDATE`,[id]);const request=requests[0];if(!request)throw new NotFoundException();const allowed:Record<string,string[]>={REQUESTED:['APPROVED','REJECTED'],APPROVED:['FULFILLED']};if(!allowed[request.status]?.includes(status))throw new BadRequestException('허용되지 않는 자원 요청 상태 전이입니다.');if(status==='APPROVED'&&request.resource_id){const updated=await manager.query(`UPDATE operational_resources SET available_quantity=available_quantity-$2,status=CASE WHEN available_quantity-$2=0 THEN 'UNAVAILABLE' WHEN available_quantity-$2<total_quantity THEN 'LIMITED' ELSE 'AVAILABLE' END,updated_at=now() WHERE resource_id=$1 AND available_quantity >= $2 RETURNING resource_id`,[request.resource_id,request.quantity]);if(!updated.length)throw new BadRequestException('가용 재고가 부족합니다.')}return (await manager.query(`UPDATE incident_resource_requests SET status=$2,updated_at=now() WHERE request_id=$1 RETURNING request_id AS "requestId",status`,[id,status]))[0];});}
  inventory(user:AuthenticatedUser){this.operator(user);return this.db.query(`SELECT resource_id AS "resourceId",resource_type AS "resourceType",name,total_quantity AS "totalQuantity",available_quantity AS "availableQuantity",unit,status,updated_at AS "updatedAt" FROM operational_resources ORDER BY resource_type,name`);}
  async addInventory(user:AuthenticatedUser,body:any){this.admin(user);if(!body.resourceType?.trim()||!body.name?.trim()||!Number.isInteger(body.totalQuantity)||body.totalQuantity<0)throw new BadRequestException();return (await this.db.query(`INSERT INTO operational_resources(resource_type,name,total_quantity,available_quantity,unit,status) VALUES($1,$2,$3,$3,$4,CASE WHEN $3=0 THEN 'UNAVAILABLE' ELSE 'AVAILABLE' END) RETURNING resource_id AS "resourceId"`,[body.resourceType.trim(),body.name.trim(),body.totalQuantity,body.unit?.trim()||'개']))[0];}
  async createFloor(incidentId:string,user:AuthenticatedUser,body:any){this.operator(user);if(!body.floorLabel?.trim()||body.widthM<=0||body.heightM<=0)throw new BadRequestException();return (await this.db.query(`INSERT INTO indoor_floors(incident_id,floor_label,width_m,height_m) VALUES($1,$2,$3,$4) RETURNING floor_id AS "floorId",floor_label AS "floorLabel"`,[incidentId,body.floorLabel.trim(),body.widthM,body.heightM]))[0];}
  async marker(incidentId:string,user:AuthenticatedUser,body:any){if(!['ENTRY','HAZARD','RESPONDER','VICTIM','RESOURCE','EXIT'].includes(body.markerType)||!body.label?.trim()||body.xPercent<0||body.xPercent>100||body.yPercent<0||body.yPercent>100)throw new BadRequestException();return (await this.db.query(`INSERT INTO operational_markers(incident_id,floor_id,marker_type,label,x_percent,y_percent,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING marker_id AS "markerId"`,[incidentId,body.floorId||null,body.markerType,body.label.trim(),body.xPercent,body.yPercent,user.userId]))[0];}
  async packet(incidentId:string,user:AuthenticatedUser,body:any){this.operator(user);if(!body.agencyName?.trim()||!['PUBLIC','OPERATIONAL','RESTRICTED'].includes(body.classification)||!body.summary?.trim())throw new BadRequestException();return (await this.db.query(`INSERT INTO collaboration_packets(incident_id,agency_name,classification,summary,created_by) VALUES($1,$2,$3,$4,$5) RETURNING packet_id AS "packetId",status`,[incidentId,body.agencyName.trim(),body.classification,body.summary.trim(),user.userId]))[0];}
  async sharePacket(id:string,user:AuthenticatedUser){this.operator(user);const packet=(await this.db.query(`SELECT incident_id FROM collaboration_packets WHERE packet_id=$1`,[id]))[0];if(!packet)throw new NotFoundException();await this.orgScope.assertIncident(user,packet.incident_id);const rows=await this.db.query(`UPDATE collaboration_packets SET status='APPROVED',approved_by=$2 WHERE packet_id=$1 AND status IN ('DRAFT','FAILED') RETURNING packet_id AS "packetId",incident_id AS "incidentId",agency_name AS "agencyName",classification,summary`,[id,user.userId]);if(!rows.length)throw new BadRequestException('초안 또는 실패 상태만 전송할 수 있습니다.');const row=rows[0];await this.db.query(`INSERT INTO durable_jobs(job_type,idempotency_key,payload) VALUES('INTERAGENCY',$1,$2::jsonb) ON CONFLICT(idempotency_key) DO UPDATE SET status='PENDING',next_attempt_at=now(),last_error=NULL`,[`interagency:${id}`,JSON.stringify(row)]);return {packetId:id,status:'APPROVED'};}
  models(user:AuthenticatedUser){this.operator(user);return this.db.query(`SELECT model_version_id AS "modelVersionId",model_name AS "modelName",version,status,deployed_at AS "deployedAt",metadata,created_at AS "createdAt" FROM ai_model_versions ORDER BY created_at DESC`);}
  async addModel(user:AuthenticatedUser,body:any){this.admin(user);if(!body.modelName?.trim()||!body.version?.trim()||!['CANDIDATE','ACTIVE'].includes(body.status))throw new BadRequestException();return this.db.manager.transaction(async manager=>{if(body.status==='ACTIVE')await manager.query(`UPDATE ai_model_versions SET status='RETIRED' WHERE model_name=$1 AND status='ACTIVE'`,[body.modelName.trim()]);return (await manager.query(`INSERT INTO ai_model_versions(model_name,version,status,deployed_at,metadata,created_by) VALUES($1,$2,$3::varchar,CASE WHEN $3::varchar='ACTIVE' THEN now() ELSE NULL END,$4::jsonb,$5::uuid) RETURNING model_version_id AS "modelVersionId"`,[body.modelName.trim(),body.version.trim(),body.status,JSON.stringify(body.metadata??{}),user.userId]))[0];});}
  async threshold(user:AuthenticatedUser,body:any){this.admin(user);if(!body.modelName?.trim()||!body.thresholdName?.trim()||typeof body.newValue!=='number'||!body.reason?.trim())throw new BadRequestException();const previous=await this.db.query(`SELECT new_value FROM ai_threshold_history WHERE model_name=$1 AND threshold_name=$2 ORDER BY changed_at DESC LIMIT 1`,[body.modelName,body.thresholdName]);return (await this.db.query(`INSERT INTO ai_threshold_history(model_name,threshold_name,old_value,new_value,reason,changed_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING threshold_id AS "thresholdId"`,[body.modelName,body.thresholdName,previous[0]?.new_value??null,body.newValue,body.reason.trim(),user.userId]))[0];}
  async readiness(user:AuthenticatedUser){this.operator(user);const [alerts,outbox,commands,sop,backup]=await Promise.all([this.db.query(`SELECT count(*) FILTER(WHERE d.received_at IS NULL)::int AS "unreceived",count(*) FILTER(WHERE d.acknowledged_at IS NULL)::int AS "unacknowledged" FROM alert_deliveries d JOIN alerts a ON a.alert_id=d.alert_id JOIN incidents i ON i.incident_id=a.incident_id WHERE i.status<>'CLOSED'`),this.db.query(`SELECT count(*) FILTER(WHERE n.status IN ('FAILED','UNAVAILABLE'))::int AS "failedChannels" FROM notification_channel_attempts n JOIN alerts a ON a.alert_id=n.alert_id JOIN incidents i ON i.incident_id=a.incident_id WHERE i.status<>'CLOSED'`),this.db.query(`SELECT count(*) FILTER(WHERE status='OPEN')::int AS "openCommands" FROM incident_commands`),this.db.query(`SELECT count(*) FILTER(WHERE status='PENDING' AND required)::int AS "pendingRequiredSop" FROM incident_sop_items`),this.db.query(`SELECT checkpoint_id AS "checkpointId",created_at AS "createdAt",restore_verified AS "restoreVerified",verified_at AS "verifiedAt" FROM recovery_checkpoints ORDER BY created_at DESC LIMIT 1`)]);return {...alerts[0],...outbox[0],...commands[0],...sop[0],latestRecoveryCheckpoint:backup[0]??null,notificationUptimeSeconds:Math.round(process.uptime())};}
  async checkpoint(user:AuthenticatedUser,body:any){this.admin(user);if(!body.artifactRef?.trim()||!/^[a-f0-9]{64}$/i.test(body.checksumSha256))throw new BadRequestException('백업 참조와 SHA-256을 확인하세요.');return (await this.db.query(`INSERT INTO recovery_checkpoints(artifact_ref,checksum_sha256,created_by) VALUES($1,$2,$3) RETURNING checkpoint_id AS "checkpointId"`,[body.artifactRef.trim(),body.checksumSha256.toLowerCase(),user.userId]))[0];}
  async verifyCheckpoint(id:string,user:AuthenticatedUser){this.admin(user);const rows=await this.db.query(`UPDATE recovery_checkpoints SET restore_verified=true,verified_by=$2,verified_at=now() WHERE checkpoint_id=$1 RETURNING checkpoint_id AS "checkpointId",restore_verified AS "restoreVerified"`,[id,user.userId]);if(!rows.length)throw new NotFoundException();return rows[0];}
}
